### ISSUE TITLE
[Bug] GitHub Rate Limit Issue with CLI

### ISSUE THREAD

**Issue by iandvt** [Azure/azure-devops-cli-extension#873] opened 2019-11-06 18:51 UTC
**Describe the bug**
```
Unable to configure a service on the selected GitHub repository. GitHub returned the error 'API rate limit exceeded
 for 13.86.33.223. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documen
tation for more details.)'.
```

**To Reproduce**
Azure CLI Version: 2.0.75
Azure-DevOps extension Version:  0.13.0
```
az pipelines create \
    --organization \
    --project \
    --service-connection  \
    --repository \
    --skip-first-run \
    --folder-path  \
    --name  \
    --branch \
    --yaml-path 
```
**Expected behavior**
I expect the CLI command to authenticate properly (aka no rate limit issues) with GitHub.

**Comment by atbagga** [comment] 2019-11-07 06:06
@iandvt The pipelines create command asks for GitHub PAT or credentials to do any operations on GitHub and should NOT be making unauthenticated requests. To help me debug the error you faced, can you share the details of the repro?

1. Complete command signature you used to invoke. (e.g. az pipelines create --name <> --service-endpoint <> --yaml-path <>
2. Did you run the command in an automated environment in a loop
3. Are you able to consistently repro it with the steps you have.

**Comment by atbagga** [comment] 2019-11-12 05:28
@iandvt Can you please share the steps for repro to help us debug this further. 
Thanks!

**Comment by geverghe** [comment] 2019-11-15 06:32
Closing this due to lack of information to reproduce on our end. @iandvt - feel free to reopen the issue when you have more information that can help us debug the issue.

**Closed by geverghe** 2019-11-15 06:32 UTC
Labels: Area: ProToCol, bug

**Comment by iandvt** [comment] 2019-11-22 16:29
@atbagga - The authentication is my example comes from the `service connection` parameter and is of type GitHub. I believe the rate limit occurs because this `service connection` is treated as singleton and referenced across my organizations Azure DevOps Project for Pipelines, Releases, etc.
