### ISSUE TITLE
failed to download universal artifacts

### ISSUE THREAD

**Issue by mkc-bruce** [Azure/azure-devops-cli-extension#899] opened 2019-11-26 09:54 UTC
## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.12.0.`

**Errors:**
```
[WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
pip-install-mjd5h3hf\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 652, in _run_job
azext_devops\dev\common\exception_handler.py, ln 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
...
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.77

Extensions:
azure-devops 0.12.0

```

**Comment by apluche** [comment] 2019-11-26 18:41
Hi,
@mkc-bruce Could you please share the debug logs for more accurate troubleshooting?
Please run the same command with --debug.

**Comment by apluche** [comment] 2019-12-06 17:44
There are new azure-cli and azure-devops extension versions available as well. Please consider updating the tools before sending the debug logs just so you have the latest fixes. Thanks!

**Comment by shubham90** [comment] 2019-12-13 00:48
This bug occurs when some other process might interfere with the download artifact tool. The process could be an antivirus, some other process which is sharing the same location etc. We are in the process of adding a retry to fix this. 

Also, this issue looks like a duplicate of #798 . Closing this one and tracking it there.

**Closed by shubham90** 2019-12-13 00:48 UTC
Labels: Area: Packages, bug
