### ISSUE TITLE
az repos list hangs

### ISSUE THREAD

**Issue by ironyman** [Azure/azure-devops-cli-extension#944] opened 2020-02-03 21:14 UTC
## Describe the bug
hangs, doesn't work

cyl@diamat:~/LSG-linux-yocto$ az repos list --verbose
^Ccommand ran in 3802.346 seconds.

**Command Name**
`az repos list
Extension Name: azure-devops. Version: 0.17.0.`

**Errors:**

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az repos list --verbose`

## Environment Summary
```
Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80

Extensions:
azure-devops 0.17.0

```

**Comment by atbagga** [comment] 2020-02-04 09:57
@ironyman 
The command works for me so the issue is definitely limited to the environment/organization. Please help me with the answers below to troubleshoot - 

- Is this consistently reproducible behavior or it happened one time?
- Is the command hang issue limited to az repos list command or is it across other az repos/az devops/az commands? 

Can you run the command with the issue in debug mode and share the output (run with --debug flag)?
This will help in figuring out where the command was stuck.

**Comment by ironyman** [comment] 2020-02-04 19:57
It did happen everytime I ran it. But az repos list is working now. I signed out and signed in and deleted some stuff. Can't quite remember everything I did.

But this is hanging
```
echo $USERPAT | az devops login --organization https://msazure.visualstudio.com --verbose --debug
```
This happens everytime.
```
azext_devops.devops_sdk.client : Api version '5.0-preview.1'
azext_devops.devops_sdk.client : GET https://msazure.visualstudio.com/_apis/ConnectionData
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): msazure.visualstudio.com:443
urllib3.connectionpool : https://msazure.visualstudio.com:443 "GET /_apis/ConnectionData HTTP/1.1" 200 694
azext_devops.devops_sdk.client : Response content: b'{"authenticatedUser": censored
keyring.backend : Loading KWallet
keyring.backend : Loading SecretService
keyring.backend : Loading Windows
keyring.backend : Loading chainer
keyring.backend : Loading macOS
Keyring backend : keyring.backends.SecretService.Keyring (priority: 5)
```
hangs there

I have a stack trace at that point

```
File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 49, in <module>
    exit_code = cli_main(az_cli, sys.argv[1:])
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 38, in cli_main
    return cli.invoke(args)
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 601, in execute
    results, exceptions = self._run_jobs_serially(jobs, ids)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/team/credentials.py", line 31, in credential_set
    set_credential(organization=organization, token=token)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/_credentials.py", line 33, in set_credential
    cred_store.set_password(key, token)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/credential_store.py", line 31, in set_password
    old_token = keyring.get_password(key, self._USERNAME)
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/backends/SecretService.py", line 64, in get_password
    collection = self.get_preferred_collection()
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/backends/SecretService.py", line 56, in get_preferred_collection
    collection.unlock()
  File "/home/cyl/.azure/cliextensions/azure-devops/secretstorage/collection.py", line 67, in unlock
    return unlock_objects(self.connection, [self.collection_path])
  File "/home/cyl/.azure/cliextensions/azure-devops/secretstorage/util.py", line 154, in unlock_objects
    dismissed, (signature, unlocked) = exec_prompt(connection, prompt)
  File "/home/cyl/.azure/cliextensions/azure-devops/secretstorage/util.py", line 140, in exec_prompt
    connection.recv_messages()
  File "/home/cyl/.azure/cliextensions/azure-devops/jeepney/integrate/blocking.py", line 62, in recv_messages
    b = self.sock.recv(4096)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/__main__.py", line 21, in quit_handler
    traceback.print_stack()
```

**Comment by ssrobins** [comment] 2020-02-11 06:27
I reported a similar issue:
https://github.com/Azure/azure-devops-cli-extension/issues/948
I worked around it by installing version 0.12.0 of the extension. Does that work for you?

**Comment by ishitam8** [comment] 2020-02-17 10:09
Hi @ironyman ,

Are you running this command interactively or within a script?

> echo $USERPAT | az devops login --organization https://msazure.visualstudio.com --verbose --debug

If not, can you try running the command interactively?
Also, is there a prompt to enter password for SecureStorage?
Or any other warning or error?

**Comment by ironyman** [comment] 2020-03-18 23:55
It was failing in a script and I ran it interactively when I tried to debug it. There as no prompt. I was running it in an ssh session. That's the full output no other error.

I tried running it again and it logged in successfully with this error message
```
keyring.backend : Loading KWallet
keyring.backend : Loading SecretService
keyring.backend : Loading Windows
keyring.backend : Loading chainer
keyring.backend : Loading macOS
Keyring backend : keyring.backends.SecretService.Keyring (priority: 5)
Failed to store PAT using keyring; falling back to file storage.
You can clear the stored credential by running az devops logout.
Refer https://aka.ms/azure-devops-cli-auth to know more on sign in with PAT.
Keyring failed. ERROR :Failed to unlock the collection!
Storing credentials in the file: /home/cyl/.azure/azuredevops/personalAccessTokens
Another organization is already set as default.
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x7fbed61ff8c8>, <function _x509_from_base64_to_hex_transform at 0x7fbed61ff950>]
Event: CommandInvoker.OnFilterResult []
Event: Cli.PostExecute []
az_command_data_logger : exit code: 0
telemetry.save : Save telemetry record of length 2564 in cache
telemetry.check : Negative: The /home/cyl/.azure/telemetry.txt was modified at 2020-03-18 16:50:51.857824, which in less than 600.000000 s
command ran in 0.636 seconds.
```

but it logged in and other commands work. Not sure what happened but it works now. I did do apt update recently so maybe one of those keyring libs were borked and they fixed it.

**Comment by ishitam8** [comment] 2020-03-19 05:36
@ironyman ,
As you can see from the when logs and the warning, when keyring fails we fallback to filestorage for linux.

> Keyring backend : keyring.backends.SecretService.Keyring (priority: 5)
Failed to store PAT using keyring; falling back to file storage.
You can clear the stored credential by running az devops logout.
Refer https://aka.ms/azure-devops-cli-auth to know more on sign in with PAT.
Keyring failed. ERROR :Failed to unlock the collection!

If you can fix the Secret storage on your system, do az devops logout and then login again, you will be able to store the credentials in your secure storage now. Check [this](https://github.com/Azure/azure-devops-cli-extension/issues/821) issue.
Otherwise it will just continue using filestorage.
Another option is to create environment variable named AZURE_DEVOPS_EXT_PAT and store your PAT in environment variable.

**Comment by roshan-sy** [comment] 2022-01-03 04:46
@ironyman
You are still facing this?
or shall we close this bug?

**Comment by roshan-sy** [comment] 2022-01-24 05:13
It is not happening anymore and we are closing this
If you are facing this issue feel free to re-open it

**Closed by roshan-sy** 2022-01-24 05:13 UTC
Labels: bug, Area: ProToCol
