### ISSUE TITLE
az pipelines build list error on fresh install

### ISSUE THREAD

**Issue by motowilliams** [Azure/azure-devops-cli-extension#751] opened 2019-08-08 23:41 UTC
## Describe the bug

**Command Name**
`az pipelines build list
Extension Name: azure-devops. Version: 0.2.0.`

**Errors:**
```
The requested resource requires user authentication: https://dev.azure.com/clearmeasure/_apis
Traceback (most recent call last):
pip-install-rtk110ve\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-rtk110ve\six\six.py, ln 693, in reraise
...
pip-install-rtk110ve\vsts\vsts\vss_client.py, ln 64, in _send_request
pip-install-rtk110ve\vsts\vsts\vss_client.py, ln 260, in _handle_error
vsts.exceptions.VstsAuthenticationError: The requested resource requires user authentication: https://dev.azure.com/clearmeasure/_apis
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az pipelines build list`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.70

Extensions:
azure-devops 0.2.0

```

**Comment by atbagga** [comment] 2019-08-12 05:20
Firstly, you are on a  very old version of the extension. Please update it via ```az extension update -n azure-devops```. You might see a better error in the latest version.

The issue here seems to be wrong or no login, did you do ```az login``` or ```az devops login```?

1. Please run login command and try again with the latest version of the extension.
2. If issue persists, use --debug flag with the command to get detailed output and share with us on the issue so we can debug further. 
**Make sure you remove any secrets or personally identifiable information from the debug logs.

**Comment by atbagga** [comment] 2019-08-19 04:46
@motowilliams Please take a look at my above comment to see if it resolves the issue for you.

**Comment by atbagga** [comment] 2019-08-27 11:34
Closing the issue. Feel free to open a new issue if it is still reproducible after upgrading to latest extension.

**Closed by atbagga** 2019-08-27 11:34 UTC
