### ISSUE TITLE
az artifacts universal download fails due to misconfigured python module dependecies.

### ISSUE THREAD

**Issue by praveen-pk** [Azure/azure-devops-cli-extension#823] opened 2019-10-14 17:46 UTC
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.13.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Linux-4.9.13-moby-x86_64-with-centos-7.6.1810-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.74

Extensions:
alias 0.5.2
log-analytics 0.1.3
azure-devops 0.13.0
subscription 0.1.3

```

**Comment by praveen-pk** [comment] 2019-10-14 18:08
```
 /root/.azure/cliextensions/azure-devops/azext_devops/dev/common/uuid.py
```
Seems like uuid module at the above path is being used which does not have uuid4() method defined.

**Comment by elbatk** [comment] 2019-10-22 15:55
Closing this one as a duplicate of #828 which has some more info

**Closed by elbatk** 2019-10-22 15:55 UTC
Labels: Area: Packages, bug, help wanted

**Comment by activey** [comment] 2019-11-07 13:45
@elbatk what "more info" are you refering to? There is nothing in the issue you are pointing out ...
