### ISSUE TITLE
[Bug] Error on artifacts publish: "Failed to hash a page of files. Exception listed below"

### ISSUE THREAD

**Issue by OskiKervinen-MF** [Azure/azure-devops-cli-extension#749] opened 2019-08-08 11:44 UTC
**Describe the bug**
When I try to upload a file to Azure Artifacts Universal feed, I receive the error "Failed to hash a page of files. Exception listed below". No exception is listed below.

**To Reproduce**
Azure Cli Version: 2.0.70

Azure-Devops extension version: 0.12.0

1. login using `az devops login --organization <org>` + input Personal Access Token
2. execute command `az artifacts universal publish --organization "<org>" --feed "Installers" --name "txt.tmp" --version "0.0.1" --description "Test upload" --path .\txt.tmp`
4. See error `Failed to hash a page of files. Exception listed below...`

**Expected behavior**
The file is uploaded to the feed. Or a clear error telling why it failed.

**Debug logs**
```
PS C:\Users\Developer\Documents\RAM> az artifacts universal publish --organization "https://dev.azure.com/my-org" -
-feed "Installers" --name "txt.tmp" --version "0.0.1" --description "Test upload" --path .\txt.tmp --debug
Command arguments: ['artifacts', 'universal', 'publish', '--organization', 'https://dev.azure.com/my-org', '--feed', 'Installers', '--name', 'txt.tmp', '--version', '0.0.1', '--description', 'Test upload', '--path', '.\\txt.tmp', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x036D8078>, <function OutputProducer.on_global_arguments at 0x0359EC90>, <function CLIQuery.on_global_arguments at 0x035C1D68>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appconfig', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.007 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.006 seconds.
Loaded module 'appconfig' in 0.003 seconds.
Loaded module 'appservice' in 0.008 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.009 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.002 seconds.
Loaded module 'botservice' in 0.004 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.003 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.002 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.003 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.005 seconds.
Loaded module 'dls' in 0.003 seconds.
Loaded module 'dms' in 0.005 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.003 seconds.
Loaded module 'hdinsight' in 0.003 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'managedservices' in 0.002 seconds.
Loaded module 'maps' in 0.002 seconds.
Loaded module 'monitor' in 0.005 seconds.
Loaded module 'natgateway' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.004 seconds.
Loaded module 'network' in 0.026 seconds.
Loaded module 'policyinsights' in 0.003 seconds.
Loaded module 'privatedns' in 0.005 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.006 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.040 seconds.
Loaded module 'vm' in 0.014 seconds.
Loaded all modules in 0.271 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: 'C:\Users\Developer\.azure\cliextensions'
Found 1 extensions: ['azure-devops']
Extensions directory: 'C:\Users\Developer\.azure\cliextensions'
Extension compatibility result: is_compatible=True cli_core_version=2.0.70 min_required=2.0.49 max_required=None
Extensions directory: 'C:\Users\Developer\.azure\cliextensions'
Loaded extension 'azure-devops' in 0.031 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03761348>]
az_command_data_logger : command args: artifacts universal publish --organization {} --feed {} --name {} --version {} --description {} --path {} --debug
metadata file logging enabled - writing logs to 'C:\Users\Developer\.azure\commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03775930>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03717B70>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03717C48>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x04780078>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0359ECD8>, <function CLIQuery.handle_query_parameter at 0x035C1DB0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03717C00>, <function handler at 0x0482FFA8>, <function DevCommandsLoader.post_parse_args at 0x04D37A08>]
Extensions directory: 'C:\Users\Developer\.azure\cliextensions'
Extensions directory: 'C:\Users\Developer\.azure\cliextensions'
az_command_data_logger : extension name: azure-devops
az_command_data_logger : extension version: 0.12.0
Checking for a new ArtifactTool
Checking for ArtifactTool updates
Getting credential: azdevops-cli:https://dev.azure.com/my-org
keyring.backend : Loading KWallet
keyring.backend : Loading SecretService
keyring.backend : Loading Windows
keyring.backend : Loading chainer
keyring.backend : Loading macOS
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
PAT is present which can be used against this instance
Current cloud config:
AzureCloud
az login is not present
There are no active accounts.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\_profile.py", line 475, in get_current_account_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\_profile.py", line 484, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Developer\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 61, in _get_credentials
    token_from_az_login = get_token_from_az_logins(organization, pat_token_present)
  File "C:\Users\Developer\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 118, in get_token_from_az_logins
    dummy_user = profile.get_current_account_user()     # noqa: F841
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\_profile.py", line 477, in get_current_account_user
knack.util.CLIError: There are no active accounts.
Getting credential: azdevops-cli:https://dev.azure.com/my-org
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
Creating connection with personal access token.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Current cloud config:
AzureCloud
Azure devops telemetry enabled.
Logging telemetry to azure devops server.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache : Loading cache file: C:\Users\Developer\.azure-devops\python-sdk\cache\options.json
azext_devops.devops_sdk._file_cache : attempting to read file C:\Users\Developer\.azure-devops\python-sdk\cache\options.json as utf-8-sig
azext_devops.devops_sdk.client : File cache hit for options on: https://dev.azure.com/my-org
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache : Loading cache file: C:\Users\Developer\.azure-devops\python-sdk\cache\resources.json
azext_devops.devops_sdk.client : Route template: _apis/{area}/{resource}
azext_devops.devops_sdk._file_cache : attempting to read file C:\Users\Developer\.azure-devops\python-sdk\cache\resources.json as utf-8-sig
azext_devops.devops_sdk.client : Api version '5.0-preview.1'
azext_devops.devops_sdk.connection : File cache hit for resources on: https://dev.azure.com/my-org
azext_devops.devops_sdk.client : POST https://dev.azure.com/my-org/_apis/CustomerIntelligence/Events
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Looking up current version of ArtifactTool...azext_devops.devops_sdk.client : Request content: [{'area': 'AzureDevopsCli', 'feature': 'artifacts', 'properties': {'Command': 'universal publish', 'Args': 'feed name version path description organization', 'ShellType': 'cmd', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': True, 'ProjectPresentInCommand': False, 'RepoPresentInCommand': False}}]

msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): dev.azure.com:443
azext_devops.devops_sdk.client : File cache hit for options on: https://my-org.vsblob.visualstudio.com
azext_devops.devops_sdk.client : Route template: _apis/{area}/{toolName}/{resource}
azext_devops.devops_sdk.client : Api version '5.0-preview'
azext_devops.devops_sdk.client : GET https://my-org.vsblob.visualstudio.com/_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): my-org.vsblob.visualstudio.com:443
urllib3.connectionpool : https://dev.azure.com:443 "POST /my-org/_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
urllib3.connectionpool : https://my-org.vsblob.visualstudio.com:443 "GET /_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64 HTTP/1.1" 200 446
azext_devops.devops_sdk.client : Response content: b'{"name":"ArtifactTool","rid":"win10-x64","version":"0.2.101","uri":"https://004vsblobprodeus2116.vsblob.vsassets.io/artifacttool/artifacttool-win10-x64-Release_0.2.101.zip?sv=2017-04-17&sr=b&sig=8PDCRKjMOGBLNf6hGl1f5ppTV7XW9x3ugHO3oKueT0I%3D&spr=https&se=2019-08-08T12%3A09%3A33Z&sp=r&P1=1565265873&P2=11&P3=2&P4=ysDP%2fH%2byNNqYiitktwoQGwnKkAHgcfm2gyneDKcwE%2bE%3d"}'
Checking if we already have ArtifactTool release 'ArtifactTool_win10-x64_0.2.101'
Not updating ArtifactTool because the current release already exists at 'C:\Users\Developer\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.101'
Getting credential: azdevops-cli:https://dev.azure.com/my-org
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
PAT is present which can be used against this instance
Current cloud config:
AzureCloud
az login is not present
There are no active accounts.
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\_profile.py", line 475, in get_current_account_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\_profile.py", line 484, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Developer\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 61, in _get_credentials
    token_from_az_login = get_token_from_az_logins(organization, pat_token_present)
  File "C:\Users\Developer\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 118, in get_token_from_az_logins
    dummy_user = profile.get_current_account_user()     # noqa: F841
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-rtk110ve\azure-cli-core\azure\cli\core\_profile.py", line 477, in get_current_account_user
knack.util.CLIError: There are no active accounts.
Getting credential: azdevops-cli:https://dev.azure.com/my-org
Keyring backend : keyring.backends.Windows.WinVaultKeyring (priority: 5)
Creating connection with personal access token.
Running external command: C:\Users\Developer\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.101\artifacttool universal publish --service https://dev.azure.com/my-org --patvar AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR --feed Installers --package-name txt.tmp --package-version 0.0.1 --path .\txt.tmp --description Test upload
Ensuring that the package does not yet exist...
Package does not yet exist
Pushing content...
DedupManifestArtifactClient will correlate http requests with X-TFS-Session c82582ed-9262-4c33-9cf7-0906842ca9fd
1 files to be processed in 1 groups.
handling generic error
cli.azure.cli.core.util : Failed to hash a page of files. Exception listed below...
Failed to hash a page of files. Exception listed below...
az_command_data_logger : exit code: 1
Suppress exception There are no active accounts.
Suppress exception Please run 'az login' to setup account.
telemetry.save : Save telemetry record of length 2434 in cache
telemetry.check : Returns Positive.
telemetry.main : Begin creating telemetry upload process.
telemetry.process : Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\Developer\.azure"
telemetry.process : Return from creating process
telemetry.main : Finish creating telemetry upload process.
command ran in 5.353 seconds.
PS C:\Users\Developer\Documents\RAM>
```

**Additional context**
The feed I tried to push to is currently empty.

**Comment by magleaso** [comment] 2019-08-12 17:58
This line is drawing my attention:

`knack.util.CLIError: Please run 'az login' to setup account.`

Have you run az login?

**Comment by OskiKervinen-MF** [comment] 2019-08-13 07:17
No. As the reproduction steps state, I used `az devops login --organization <org>` to log in with a personal access token, which is not possible with `az login`.

**Comment by Skorodum** [comment] 2019-08-15 11:07
Got the similar error message but with vsts:

>vsts package universal publish --instance "https://dev.azure.com/xxx/" --feed TestFeed --name "xxx" --version 0.0.1 --path . --debug
>....
> 168 files to be processed in 2 groups.
Failed to hash a page of files. Exception listed below...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 212, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\universal.py", line 41, in publish_package
    return artifact_tool.publish_universal(team_instance, feed, name, version, description, path)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 30, in publish_universal
    return self.run_artifacttool(team_instance, args, "Publishing")
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 44, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, self._process_stderr)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\external_tool.py", line 72, in run
    stderr_handler(line, self._update_progress)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 64, in _process_stderr
    self._log_message(json_line)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 76, in _log_message
    raise CLIError(message)
knack.util.CLIError: Failed to hash a page of files. Exception listed below...
Failed to hash a page of files. Exception listed below...

**Comment by apluche** [comment] 2019-08-21 23:37
Looks these errors are caused by the issue reported in this bug: [Universal artifacts publish - path attribute cannot start with '.\'](https://github.com/Azure/azure-devops-cli-extension/issues/757). The error occurs when the files are referenced with ".\" .

**Comment by nuno-barreiro** [comment] 2019-09-19 10:47
The feedback from @apluche is correct. Had the same issue when trying to pass ```--path .\filename.ext```. Changing that to ```--path filename.ext``` solved the issue

**Comment by sorvis** [comment] 2019-10-08 14:09
I'm seeing this as well, but the "." dot in the path does not matter. The error message does not seem to give very much to go on.

> Ensuring that the package does not yet exist...
> Package does not yet exist
> Pushing content...
> DedupManifestArtifactClient will correlate http requests with X-TFS-Session 6d836b00-2731-4788-94c3-9433fc6486a0
> 1 files to be processed in 1 groups.
> handling generic error
> cli.azure.cli.core.util : Failed to hash a page of files. Exception listed below...
> Failed to hash a page of files. Exception listed below...
> az_command_data_logger : exit code: 1
> telemetry.save : Save telemetry record of length 2625 in cache
> telemetry.check : Negative: The /root/.azure/telemetry.txt was modified at 2019-10-08 10:00:15.924218, which in less than 600.000000 s
> command ran in 3.364 seconds.
> 

I'm using Ubuntu 14.04.6 LTS with these versions of the az tool:

> azure-cli                         2.0.74
> 
> command-modules-nspkg              2.0.3
> core                              2.0.74
> nspkg                              3.0.4
> telemetry                          1.0.3
> 
> Extensions:
> azure-devops                      0.13.0

**Comment by elbatk** [comment] 2019-10-22 15:38
@apluche it looks like you took a look at this one before, mind taking another around?

**Comment by lp-code** [comment] 2020-01-07 08:59
For me, the name specified after --path contained dots (".") as part of version number. Passing a directory name without dots solved the issue.

**Comment by sorvis** [comment] 2020-01-07 16:52
Similar to lp-code my issue I later resolved by using a directory. At first I had tried referencing a file directly which caused the error for me. I think that should be considered a bug that it cannot take a file directly without producing a logical error message.

**Comment by elduddz** [comment] 2020-04-24 11:39
> Similar to lp-code my issue I later resolved by using a directory. At first I had tried referencing a file directly which caused the error for me. I think that should be considered a bug that it cannot take a file directly without producing a logical error message.

I did the same, created a directory with this in (I did have dots in the name) and it worked

**Comment by mjiderhamn** [comment] 2020-05-25 10:31
I would like to clarify that you can publish a ZIP file *from the current directory*, but you get this error message if you try to include a path (in addition to filename) in the `--path` parameter.

I.e. this does not work
```
c:\foo> az artifacts universal publish ... --path bar\baz.zip
```
nor does this
```
c:\foo\bar> az artifacts universal publish ... --path .\baz.zip
```
while this works
```
c:\foo\bar> az artifacts universal publish ... --path baz.zip
```

**Comment by jontreynes** [comment] 2020-06-08 16:00
I am getting this error even when leaving out the period
![image](https://user-images.githubusercontent.com/19974635/84053271-ac9afa80-a97f-11ea-85e9-83de65c04fba.png)

**Comment by jontreynes** [comment] 2020-06-08 16:08
btw. Works just fine on windows with @mjiderhamn's working example
`c:\foo\bar> az artifacts universal publish ... --path baz.zip`

```
[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "azure-devops",
    "path": "C:\\Users\\joreynes\\.azure\\cliextensions\\azure-devops",
    "preview": false,
    "version": "0.18.0"
  }
]
```

**Comment by mjiderhamn** [comment] 2020-06-08 16:42
@jontreynes , once you've managed to upload the ZIP file, you may hit #877

**Comment by jontreynes** [comment] 2020-06-08 19:05
yes, I did run into that @mjiderhamn... weird this was not the case on Feb 19, 2020. I was able to successfully download and upload zips all day a while back

**Comment by jontreynes** [comment] 2020-06-08 19:35
so figured out one thing..

When you publish a zip file, put the zip file in a folder with just the zip file

Then use "--path ." and it will upload the zip file as that's the only piece that exists in the folder. When you download artifact, you'll download the zip.

--path needs to receive a "DIRECTORY", not a full path
https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/artifacts/universal?view=azure-cli-latest#ext-azure-devops-az-artifacts-universal-download

**Comment by mjiderhamn** [comment] 2020-06-09 06:21
@jontreynes , unfortunately, putting a ZIP file inside your artifact is not the same thing as making the ZIP file the artifact. (You could place a ZIP file inside your ZIP file artifact as well).

The problem becomes obvious with your example above. The consumer of your artifact would need to know that inside the 0.0.2 artifact version there is a ZIP file with `v.1.0.0` in its name.

**Comment by samuelkoppes** [comment] 2020-08-24 21:50
Closing as the original problem is addressed.

**Closed by samuelkoppes** 2020-08-24 21:50 UTC
Labels: Area: Packages, bug, help wanted

**Comment by danrs** [comment] 2020-11-11 03:24
@samuelkoppes this issue thread describes a workaround (using a directory) but the issue in question is still present in the current version of the az CLI (2.14.2). I think this should be addressed with a proper error message in the failed command

**Comment by sasitha-sleevesup** [comment] 2020-11-24 02:03
specifying the absolute path on macos fixed it for me.

**Comment by wathmal** [comment] 2020-11-24 02:04
specifying the absolute path on macOS fixed it for me.

**Comment by antoniovs1029** [comment] 2021-05-10 14:24
In my case it wouldn't work until I used the full path of the file I wanted to upload

**Comment by toddwalstad-eaton** [comment] 2021-05-10 21:18
> In my case it wouldn't work until I used the full path of the file I wanted to upload

Thanks for adding this comment!  I was pulling my hair out trying to get this to work and for me this is also the only way this would work.  I have a setup.exe inside of zip and no other methods worked.

**Comment by doublethink13** [comment] 2024-04-22 20:03
2024 and this is still an issue 🤷‍♂️
