### ISSUE TITLE
[Bug] Documentation for az repos pr create --reviewers incomplete

### ISSUE THREAD

**Issue by fdcds** [Azure/azure-devops-cli-extension#733] opened 2019-07-25 13:34 UTC
**Describe the bug**

`az repos pr create --reviewers` does not appear to behave as described in the documentation.

Passing `az repos pr create --reviewers="UUID1 UUID2" ...` (UUIDs are the `id` fields from `az repos pr reviewer list --id ...` or `az devops user list | jq -r '.items[] | {id:.id, name:.user.displayName}'`) will output: `Could not resolve identity: UUID1 UUID2`.

The same goes for passing `az repos pr create --reviewers="x@example.com y@example.com" ...`, where the email address are the `uniqueName` fields from `az repos pr reviewer list --id ...` or `az devops user list | jq -r '.items[] | {email:.principalName, name:.user.displayName}'`:  `Could not resolve identity: x@example.com y@example.com`.

The documentation says the value would be split on whitespace:
```
Command
    az repos pr create : Create a pull request.

Arguments
[...]
    --reviewers             : Additional users or groups to include as reviewers on the new pull
                              request. Space separated.
```

Since the output says that the identity `UUID1 UUID2` could not be resolved, I conclude that the documentation is wrong and the argument is not actually split on whitespace.  Additionally it fails to explain how the reviewers should look like / how I can find the correct IDs / names.

**To Reproduce**
```
azure-cli                         2.0.69

command-modules-nspkg               2.0.3
core                              2.0.69
nspkg                              3.0.4
telemetry                          1.0.3

Extensions:
azure-devops                      0.11.0

Python location '/opt/az/bin/python3'
Extensions directory '$HOME/.azure/cliextensions'

Python (Linux) 3.6.5 (default, Jul 11 2019, 08:41:35)
[GCC 7.4.0]
```

1. login using az login
2. create a repository
3. Run `az repos pr create --reviewers="UUID1 UUID2" ...` (with some sensible values for UUID1 UUID2)

**Expected behavior**

1. The documentation of the `--reviewers` argument should specify how these reviewer references should look like.
2. `az repos pr create --reviewers="UUID1 UUID2" ...` with UUIDs taken from `az repos pr reviewer list --id ...` should "just work".
   - The same should probably be true when using the `uniqueName` instead of the `id`.

**Comment by atbagga** [comment] 2019-07-26 05:46
@fdcds By putting the values in quotes the system reads it as one string "UUID1 UUID2" 
The correct way to give space separate values in CLI is `--reviewers UUID1 UUID2`.

If/when the string contains a whitespace (though it will not be the case in UUID or email-id) that individual item should be enclosed in quotes e.g. `--reviewers "atul bagga" "Another Name"` will try to add the two reviewers named 'atul bagga' and 'another person'.

Refer doc [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) for more details on quoting issues.

Please let me know if that resolves the issue for you. I will add an example in the command to clarify the usage.

**Comment by fdcds** [comment] 2019-07-26 08:00
Thanks for the clarification.

I think the confusion results from the word "space separated". I would think that this commonly refers to one string with whitespace in it. What you refer to I would think is commonly called "list of arguments".

Additionally, I tried what you describe with the `--description` option and `az` complained that it could not parse my arguments. I currently do not have a PR-ready branch, but I'll get back to you with the concrete command line and error message once I do. What I ended up doing to make it work was passing `--description` one single string with newlines in it. I think the help string (output of `-h`) should also be clarified for this option.

**Comment by fdcds** [comment] 2019-07-26 12:20
It appears that this breaks when I pass the argument as `--reviewers="UUID1" "UUID2"`:
```
az: error: unrecognized arguments: UUID2
```

I expect I ran into the same issue with `--description`. There I was able to pass multiple lines in one string and did not need to split up the description string into multiple arguments, which made it less confusing.

**Comment by atbagga** [comment] 2019-07-29 07:43
@fdcds It should be `--reviewers "UUID1" "UUID2"` rather than `--reviewers="UUID1" "UUID2"`

**Comment by fdcds** [comment] 2019-07-29 12:29
I figured that out, too. (And `--reviewers=A --reviewers=B` does not work, either. The CLI will only see the latter.) It is confusing that the both appear to be supported at first, but one does not work properly.

**Comment by atbagga** [comment] 2019-07-30 06:30
Glad you could figure it out. 

Also sharing the link to the document [here](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues) again for more details on parameter issues.

Closing the issue since this is not a bug and working as expected.

**Closed by atbagga** 2019-07-30 06:30 UTC
Labels: Area: ProToCol
