### ISSUE TITLE
Issue with az artifacts command

### ISSUE THREAD

**Issue by hmundeepi** [Azure/azure-devops-cli-extension#857] opened 2019-10-31 04:21 UTC
## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.13.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} --name {} --version {} --description {} --path {}`

## Environment Summary
```
Linux-3.10.0-1062.1.2.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.75

Extensions:
azure-devops 0.13.0

```

**Comment by shubham90** [comment] 2019-12-11 21:04
This is a duplicate of bug #832 . Universal download/publish extension requires python 3.0 or above to run. This is a python version compatibility issue which should be resolved once python is updated.

**Closed by shubham90** 2019-12-11 21:04 UTC
Labels: Area: Packages, bug
