### ISSUE TITLE
Universal artifacts publish - path attribute cannot start with '.\'

### ISSUE THREAD

**Issue by pwl-kdk** [Azure/azure-devops-cli-extension#757] opened 2019-08-21 21:41 UTC
## Describe the bug
When publishing a 'universal' artifact.  Using "--path .\my-file" does not work but "--path my-file" does.

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.12.0.`

**Errors:**
```
Failed to hash a page of files. Exception listed below...
```

## To Reproduce:
Follow the steps in [Universal Quickstart](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops) (on Windows Powershell)
Publish a file to the feed without leading dot-slash ("my-file") and then with leading dot-slash (".\my-file").  
It only works without the leading dot-slash

## Expected Behavior
Expected output something like...
```
{
  "Description": "Your description",
  "ManifestId": "0478B70A269937B4961F8052F7669FF32F5B3892A96C3AF09D931EF49189623B01",
  "SuperRootId": "A78F1FA046FBFA0EB481D1569F49617D361E799D6074190432218E4751E3F69902"
}
```
## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.71

Extensions:
aks-preview 0.4.5
azure-devops 0.12.0

```

**Comment by apluche** [comment] 2019-08-21 23:39
@atbagga I unfortunately can't change the tags on this. Could you tag it as Area: Packages and bug? 

Additionally, the two open issues that are having the same errors can likely be combined into this thread. Thanks

**Comment by elbatk** [comment] 2019-10-16 20:15
@apluche hey! Did we end up fixing or logging anything here?

**Comment by elbatk** [comment] 2019-10-22 15:39
Also tagging @owenhuynMSFT and @jahsu-MSFT

**Comment by mjiderhamn** [comment] 2020-05-25 10:34
I believe this is a duplicate of https://github.com/Azure/azure-devops-cli-extension/issues/749

**Closed** 2020-09-21 21:50 UTC
Labels: Area: Packages, aa-triaged, bug, help wanted
