### ISSUE TITLE
az repos pr create to fork

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Azure/azure-devops-cli-extension#800] opened 2019-09-24 16:43 UTC
If I have a forked repository withing the same project it should be possible to create PR using CLI as this can be done through user interface.

**Comment by geverghe** [comment] 2019-09-30 10:02
Closing this issue as a duplicate of #743 . Let me know if this does not match your expectation.

**Closed by geverghe** 2019-09-30 10:02 UTC
Labels: Feature
