### ISSUE TITLE
[Feature Request] KeyVault support for az pipelines variable-group

### ISSUE THREAD

**Issue by heoelri** [Azure/azure-devops-cli-extension#916] opened 2019-12-03 13:17 UTC
**Is your feature request related to a problem? Please describe.**
We're currently working with a customer who's creating a bunch of Azure KeyVaults for several workstreams within an Azure DevOps project. They're looking for an automated way to create variable groups in Azure DevOps that are mapped to Azure KeyVaults (KV).

Currently the Azure DevOps (ADO) CLI extension supports the creation of Variable Groups (VGs) but it doesn't offer us the capability to create VGs that are mapped to a KeyVault.

**Describe the solution you'd like**
It would be great if we were able to create and configure VGs in ADO mapped to a specific KV.

```bash
az pipelines variable-group create
                         [--vault-name <KeyVaultName>]
                         [--description <description>]
                         [--name <groupname>]
                         [..]
```

**Additional context**
We were looking for a way to achieve that through Rest API calls but that requires some additional information (auth token etc) that adds additional complexity we'd like to avoid.

**Comment by atbagga** [comment] 2019-12-04 09:58
@heoelri This is duplicate of #723.

Please check my comment on that issue which should help in automating using invoke command until the explicit command is available. 

Closing the issue as Dupe. You can follow that issue for updates and any further comments/feedback.

**Closed by atbagga** 2019-12-04 09:58 UTC
Labels: Feature

**Comment by heoelri** [comment] 2019-12-04 10:03
Thanks @atbagga for pointing me to the other thread. I think `az devops invoke` helps us a lot.
