### ISSUE TITLE
linux failures on universal download

### ISSUE THREAD

**Issue by darthscsi** [Azure/azure-devops-cli-extension#913] opened 2019-12-02 18:51 UTC
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.16.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization "https://dev.azure.com/mscatapult/" --feed "FpgaTools" --name "questasimfpga.linux" --version "2019.4.0" --path 2019.4.0`

## Expected Behavior

Not crash

## Environment Summary
```
Linux-3.10.0-1062.el7.x86_64-x86_64-with-centos-7.7.1908-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.76 *

Extensions:
azure-devops 0.16.0

```
## Additional Context

Happy to collect more if needed.   MS FTEs should be able to reproduce.

**Comment by satbai** [comment] 2019-12-03 01:39
It looks like you're using Python 2.7.5. Could you update your Python to 3.6.x or 3.7.x and see if it fixes the issue? I know the [documentation](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#prerequisites) mentions that Python 2.7.x should be still compatible, but it looks like [upgrading Python](https://github.com/Azure/azure-devops-cli-extension/issues/903#issuecomment-560262397) has worked for some other people.

**Comment by satbai** [comment] 2019-12-05 18:55
I was able to reproduce this with python 2.7 and updating python to 3.6 fixed it. As the documentation mentions Python version 3.6 or 3.7 as a prerequisite, I'm closing this issue. Let me know if you still see this after updating python and I'll investigate more. Thanks!

**Closed by satbai** 2019-12-05 18:55 UTC
Labels: Area: Packages, bug
