### ISSUE TITLE
[Feature Request] az pipeline run --parameters (--variables supported but not --parameters)

### ISSUE THREAD

**Issue by aluty** [Azure/azure-devops-cli-extension#972] opened 2020-03-24 07:52 UTC
**Is your feature request related to a problem? Please describe.**
Cannot queue a pipeline that requires parameters.

**Describe the solution you'd like**
Support az pipeline run --parameters name=value

**Additional context**
Parameters were just implemented recently?

**Comment by Ashani-Quest** [comment] 2020-05-10 13:39
Any estimation for this feature? The lack of this feature prevents us from using runtime parameters within our pipelines.

**Comment by adrianmo** [comment] 2020-06-11 10:06
In the meantime, you can use the following curl command to queue a pipeline with runtime parameters. The API call is documented [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run%20pipeline?view=azure-devops-rest-6.0).

```
curl -X POST https://dev.azure.com/${DEVOPS_ORG}/${DEVOPS_PROJECT}/_apis/pipelines/${PIPELINE_ID}/runs\?api-version\=6.0-preview.1 \
     -H "Content-Type: application/json" \
     -u "${DEVOPS_PAT}": \
     -d @<(cat <<EOF
{
    "stagesToSkip": [],
    "resources": {
        "repositories": {
            "self": {
                "refName": "refs/heads/master"
            }
        }
    },
    "templateParameters": {
        "param1": "value1",
        "param2": "value2"
    },
    "variables": {}
}
EOF
)
```

**Comment by MohammedQureshi** [comment] 2020-11-26 13:36
Hi, How would I implement this into an azure DevOps pipeline I am unsure how to run the curl command?

**Comment by adrianmo** [comment] 2020-11-27 07:46
@MohammedQureshi you can use it in a `script` or `bash` task. See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example%2Cparameter-schema#script

**Comment by MohammedQureshi** [comment] 2020-11-27 10:16
I am running the pipeline on a Windows machine so I can't use bash script and I tried to do this and it failed any ideas?

  steps:
  - script: |
      curl -X POST https://dev.azure.com/{TEAM}/{PROJECT}/_apis/pipelines/{PipelineNum}/runs\?api-version\=6.0-preview.1 \
        -H "Content-Type: application/json" \
        -u "{DEVOPS_PAT}": \
          -d @<(cat <<EOF
            {
                "stagesToSkip": [],
                "resources": {
                    "repositories": {
                        "self": {
                            "refName": "refs/heads/master"
                        }
                    }
                },
                "templateParameters": {
                    "Tag": "Tag0101011",
                },
                "variables": {}
            }
          EOF
          ) 

I get this error below :( Fyi I filled in the spots I just removed them as its sensitive information 

![image](https://user-images.githubusercontent.com/34938712/100438063-97369b80-3099-11eb-8ba4-e888275f84e6.png)

**Comment by arthurdaytonSIC** [comment] 2021-01-06 21:25
plus one on this - i have been able to use rest api as workaround but super painful

**Comment by wurdack** [comment] 2021-01-29 04:57
Another plus one. Not being able to specify parameters to my builds is a gross oversight in this tool.

**Comment by tnsholding** [comment] 2021-01-29 07:23
Plus one. Really need this - but have to revert to REST api...

**Comment by Tingle01** [comment] 2021-02-03 10:28
Plus one.  This seems a massive oversight.

**Comment by SergeBerwert** [comment] 2021-02-05 17:19
I miss that too

**Comment by jacderida** [comment] 2021-02-19 11:05
The lack of this makes the `run` command almost unusable. Is there a plan to implement this soon? The issue has been open for nearly a year.

**Comment by derubiops** [comment] 2021-03-11 19:17
Yes, that would be good to have via az cli and avoid using the painful API call... Thanks to @arthurdaytonSIC for your post, it helped a lot.

**Comment by arthurdayton116** [comment] 2021-03-11 20:04
PS - If you run your pipeline in the UI and look at the network tab in developer tools you will see that MS uses same API so it makes figuring out syntax issues waaaayyyyy easier.

**Comment by mathiasgheno** [comment] 2021-03-11 22:56
I miss that feature too. Would be very helpful.

**Comment by martin77s** [comment] 2021-03-18 14:00
+1
Over a year now..

**Comment by ggirard07** [comment] 2021-03-18 21:17
Does anybody figured a way out to invoke the request through `az devops invoke` to al least handle auth?

**Comment by markdowd** [comment] 2021-03-29 19:08
Plus one here too.

**Comment by timcrall** [comment] 2021-04-07 20:44
Need this

**Comment by Wally23** [comment] 2021-05-06 10:54
+1 need this badly

**Comment by dod0o** [comment] 2021-05-06 10:55
We have 5 children at home, we need dis

**Comment by trupci** [comment] 2021-05-06 12:35
+1

**Comment by adrianmo** [comment] 2021-05-06 14:05
> Did anybody figure a way out to invoke the request through `az devops invoke` to at least handle auth?

Create a file (e.g. `body.json`) that contains the request body with the git branch and pipeline parameters.

```json
{
    "stagesToSkip": [],
    "resources": {
        "repositories": {
            "self": {
                "refName": "refs/heads/master"
            }
        }
    },
    "templateParameters": {
        "param1": "value1",
        "param2": "value2"
    },
    "variables": {}
}
```

Then do...

```
az devops invoke \
    --http-method POST \
    --area pipelines \
    --resource runs \
    --route-parameters project=<YOUR_PROJECT_NAME> pipelineId=<YOUR_PIPELINE_ID> \
    --api-version "6.0-preview" \
    --in-file body.json
```

Add the `--debug` flag if something is not working to try to find out the cause.

You can find your pipeline ID by navigating to your pipeline from DevOps and finding the `definitionId` in the URL.

It's not a solution, but at least it's better than running cURL commands...

**Comment by walliski** [comment] 2021-05-06 14:13
@adrianmo Great timing! I just stumbled upon this, that workaround will be helpful!

Also can chime in with a "+1" just to give visibility to this.

**Comment by vamsee-konda** [comment] 2021-05-12 22:36
+1, please fix.

**Comment by kandula-aswin** [comment] 2021-05-17 05:34
+1, please implement

**Comment by fabio-notified** [comment] 2021-06-23 18:35
We really need this!

**Comment by ausfestivus** [comment] 2021-07-07 22:54
Hey @gauravsaralMs, noticed that this issue has been removed from planning. Considering the support for this feature to be implemented, can MS explain why this issue has now gone backwards?

**Comment by ofiron01** [comment] 2021-07-13 18:07
+1 We need this, please implement

**Comment by ausfestivus** [comment] 2021-07-14 07:20
@ofiron01, instead of commenting with a +1, please go and click the 👍 icon on the original request [above](https://github.com/Azure/azure-devops-cli-extension/issues/972#issue-586763341).

**Comment by ausfestivus** [comment] 2021-07-15 11:53
Im pretty sure there is a dupe of this issue in https://github.com/Azure/azure-devops-cli-extension/issues/1110. Good news is is that I think its getting worked on in 1110. Maybe. Hard to be sure. The comms from MS on this issue arent great.

**Comment by roshan-sy** [comment] 2021-11-15 10:59
The mentioned requirement has been implemented
Please use the attached whl file to install the build, please try out and share feedback

Run the following command to install the build
`pip install .\azure_devops-0.23.0-py2.py3-none-any.whl`

https://github.com/roshan-sy/release-repo/releases/download/untagged-6aeb56c9fde1d991a0d8/azure_devops-0.23.0-py2.py3-none-any.whl

**Comment by roshan-sy** [comment] 2021-11-15 11:09
This build will be available in next release.

**Closed by roshan-sy** 2021-11-15 11:09 UTC
Labels: Feature, Requires API upgrade

**Comment by aluty** [comment] 2021-11-15 22:38
@roshan-sy Finally, thank you.  Ability to much more easily call pipelines from CLI should help save hours of time across a multitude of developers.

1. Small update needed to install; need to remove old package first.
The extension azure-devops already exists.
az extension remove -n azure-devops
az extension add --source https://github.com/roshan-sy/release-repo/releases/download/1/azure_devops-0.23.0-py2.py3-none-any.whl

2. Initial test looks good.
az login
az pipelines run --help
...
    --parameters         : Space separated "name=value" pairs for the parameters you would like to set.
...
az pipelines run --name "{pipeline.name}" --parameters Param1={Value1}

**Comment by pawwilgrass** [comment] 2021-11-24 11:32
@roshan-sy thanks! Great work! When version 0.23.0 will be released?

**Comment by romanrabodzei** [comment] 2021-12-29 18:52
thanks @roshan-sy and @aluty!

**Comment by aluty** [comment] 2022-01-13 05:17
Still only **azure-devops** version **0.22.0** available; when will **0.23.0** be released?

```
CMD> az extension list-available --query "[? name == 'azure-devops']"
[
  {
    "experimental": false,
    "installed": true,
    "name": "azure-devops",
    "preview": false,
    "summary": "Tools for managing Azure DevOps.",
    "version": "0.22.0"
  }
]
```

**Comment by superff** [comment] 2022-01-21 19:06
Could you give an estimate when will the feature release?

**Comment by roshan-sy** [comment] 2022-01-22 02:50
> Could you give an estimate when will the feature release?

@superff 
Sure, will let you know by Monday.

**Comment by roshan-sy** [comment] 2022-02-01 09:32
https://github.com/Azure/azure-cli-extensions/pull/4378

**Comment by roshan-sy** [comment] 2022-02-09 07:35
@superff
Released

**Comment by ludoo0d0a** [comment] 2022-03-24 12:32
Just update extensions, 0.24 is released
```
az extension update
```

**Comment by SergeBerwert** [comment] 2022-03-24 14:58
Just try to do this:

build queue --organization "https://dev.azure.com/..." --project "..." --definition-name "..."  --parameters "parameter=true"

Did not work can't find any suggestion in the documentation that --parameters are now available. what am I am doing wrong?

Did update the extension to "version": "0.24.0"

**Comment by SergeBerwert** [comment] 2022-03-24 17:06
@walliski thanks for the hint. we do use YAML pipelines but we did start them with the queue command. now it works very happy about that.

**Comment by sijucm** [comment] 2022-06-21 13:22
Really? Microsoft thought it was wise not to give option to pass parameters but variables? This company is so random and lot of bad choices. I wasted half a day thinking this is going to be the work around for lot of other issues microsoft added. Of course I'm frustrated. Just cannot believe this and this is not the first time.

**Comment by sijucm** [comment] 2022-06-21 13:41
Typical Microsoft way of implementing this change. It says in the documentation : "--parameters         : Space separated "name=value" pairs for the parameters you would like to set"

If I try 
 az pipelines run --branch xx --name nameofpipeline --organization https://dev.azure.com/orgname/ --project projet --parameters "A=x B=y" will give the error
  `"The 'A' parameter value 'x B=y' is not a valid value."` 
Of course Microsoft did not use space as a separator (and I can understand why), but the documentation is totally out of sync. And the next effort is to guess what the Microsoft "developers" find will be a good separator, and no, nothing normal works as a separator. Could someone be kind enough to check this?

**Comment by walliski** [comment] 2022-06-21 13:46
Did you try what the documentation explains: or `--parameters "A=x" "B=y"` or `--parameters A="x" B="y"`?
