### ISSUE TITLE
Access exception during installation of ArtifactTool_win10-x64_0.2.128 when downloading a package from private azure artifacts feed on Azure DevOps

### ISSUE THREAD

**Issue by astafan8** [Azure/azure-devops-cli-extension#861] opened 2019-10-31 13:25 UTC
## Describe the bug

**Command Name**
```
az artifacts universal download
```
Extension Name: azure-devops. Version: 0.13.0.

**Errors:**
```
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
pip-install-p8t_6awn\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 652, in _run_job
azext_devops\dev\common\exception_handler.py, ln 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-p8t_6awn\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
...
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

I also include the PowerShell CLI output that i got:

```
(base) PS C:\windows\system32> az artifacts universal download  --organization "$$$$$$$"  --feed "$$$$$$$"  --name "$$$$$$$" --version "0.0.1" --path .
An error occurred while extracting the Universal Packages tooling: [WinError 5] Access is denied: 'C:\\Users\\a-miasta\\.azure\\azuredevops\\cli\\tools\\artifacttool\\24c02061-ad28-4418-a045-7c773c70584a' -> 'C:\\Users\\a-miasta\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.128'
The command failed with an unexpected error. Here is the traceback:

[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 652, in _run_job
  File "C:\Users\a-miasta\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\a-miasta\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 51, in download_package
    return artifact_tool.download_universal(organization, feed, name, version, path, file_filter)
  File "C:\Users\a-miasta\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 39, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\a-miasta\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 61, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\a-miasta\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 71, in run
    self.start(command_args, env)
  File "C:\Users\a-miasta\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 39, in start
    env=env)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

After re-running the initial CLI command 3 times, the installation/download worked.

## Expected Behavior

Installation should succeed and I should see this in powershell:

```
az artifacts universal download  --organization "$$$$$$"  --feed "$$$$$"  --name "$$$$$" --version "0.0.1" --path .
{
  "Description": "$$$$$$",
  "ManifestId": "$$$$$$",
  "SuperRootId": "$$$$$",
  "Version": "0.0.1"
}
```

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.75

Extensions:
azure-devops 0.13.0

```

**Comment by shubham90** [comment] 2019-12-13 00:53
This bug occurs when some other process might interfere with the download artifact tool. The process could be an antivirus, some other process which is sharing the same location etc. We are in the process of adding a retry to alleviate this. If the antivirus policy is set to delete the tool, then the path needs to be whitelisted. 

Also, this issue looks like a duplicate of #776 . Closing this one and tracking it there.

**Closed by shubham90** 2019-12-13 00:53 UTC
Labels: Area: Packages, bug
