### ISSUE TITLE
[Bug] az pipelines create throws an error when trying to create against a repo that was previously deleted

### ISSUE THREAD

**Issue by craigmonson** [Azure/azure-devops-cli-extension#696] opened 2019-06-27 20:47 UTC
**Describe the bug**
`az pipelines create` throws an error when trying to create against a repo that was previously deleted, but recreated with the same name.

**To Reproduce**
Azure Cli Version: 
```
azure-cli                         2.0.67

acr                                2.2.9
acs                                2.4.4
advisor                            2.0.1
ams                                0.4.7
appservice                        0.2.21
backup                             1.2.5
batch                              4.0.3
batchai                           0.4.10
billing                            0.2.2
botservice                         0.2.2
cdn                                0.2.4
cloud                              2.1.1
cognitiveservices                  0.2.6
command-modules-nspkg               2.0.2
configure                         2.0.24
consumption                        0.4.4
container                         0.3.18
core                              2.0.67
cosmosdb                          0.2.11
deploymentmanager                  0.1.1
dla                                0.2.6
dls                               0.1.10
dms                                0.1.4
eventgrid                          0.2.4
eventhubs                          0.3.7
extension                          0.2.5
feedback                           2.2.1
find                               0.3.4
hdinsight                          0.3.5
interactive                        0.4.5
iot                               0.3.11
iotcentral                         0.1.7
keyvault                          2.2.16
kusto                              0.2.3
lab                                0.1.8
maps                               0.3.5
monitor                           0.2.15
natgateway                         0.1.1
network                            2.5.2
nspkg                              3.0.3
policyinsights                     0.1.4
privatedns                         1.0.2
profile                            2.1.5
rdbms                             0.3.12
redis                              0.4.4
relay                              0.1.5
reservations                       0.4.3
resource                          2.1.16
role                               2.6.4
search                             0.1.2
security                           0.1.2
servicebus                         0.3.6
servicefabric                     0.1.20
signalr                            1.0.1
sql                                2.2.5
sqlvm                              0.2.0
storage                            2.4.3
telemetry                          1.0.2
vm                                2.2.23

Extensions:
azure-devops                      0.11.0

Python location '/usr/local/Cellar/azure-cli/2.0.67/libexec/bin/python'
Extensions directory '/Users/cmonson/.azure/cliextensions'

Python (Darwin) 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

1. login using az login
2. create a repo:
```
        az repos create \
                --name $(REPO) \
                --org https://dev.azure.com/$(ORG_NAME) \
                --project $(PROJECT_NAME)
```
3. Delete the repo via the ui
4. Create the repo again
```
        az repos create \
                --name $(REPO) \
                --org https://dev.azure.com/$(ORG_NAME) \
                --project $(PROJECT_NAME)
```
5. Create a pipeline referencing the deleted and recreated repo
```
        az pipelines create \
                --name $(REPO) \
                --branch master \
                --description "Builds the $(REPO) project" \
                --yml-path "azure-pipelines.yaml" \
```
6. Raised exception:
```
TF401019: The Git repository with name or identifier XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX does not exist or you do not have permissions for the operation you are attempting.
```

**Expected behavior**
It's expected that the pipeline would be created, referencing the newly created repo.

**Screenshots**
The cli is pretty and all, but I don't think a screenshot is necessary ;)

**Debug logs**
I'll add later if necessary, as there's client related info in it.

**Additional context**
We are creating automation that creates a repo, an associated pipeline, and an associated release.  This is working fine.  This was found when trying to clean up (and re-run) testing code.  We went into the web ui, deleted each of the resources, then attempted to re-run the automation.

**Comment by atbagga** [comment] 2019-07-15 09:30
@craigmonson Sorry for late response. I am trying to verify this issue and it seems this works fine if you try to create a pipeline on a recreated repo of same name. 

**Here is what I tried..** 

1. Create a repo from CLI. 
2. Delete it from UI.
3. Create repo with same name again from CLI. 
4. Initialize and add a yaml file in the repo. 
5. Create a pipeline using command - 
```
az pipelines create --name mypipeline1 --branch master --description "test description" --yml-path azure-pipelines.yaml --repository repo1 --repository-type tfsgit
```

**Probable issue in your case:** 
From the commands you posted your `az pipelines create` command does not have the repository info (--repository, --repository-type) in that case it will be auto detected from the folder where the command is executed from if the folder is a checked out git repo. If that is not intentional probably that is causing the issue for you. 

Please let me know if this helps.

**Comment by atbagga** [comment] 2019-07-19 06:35
@craigmonson Please verify the behavior as per above comment. If that is the case this is not an issue.

**Comment by atbagga** [comment] 2019-07-21 06:52
@craigmonson The issue is not reproducible. Closing for now with above analysis. 
Please feel free to open a new issue or tag me and comment here if you still have the issue and I will reopen it.

**Closed by atbagga** 2019-07-21 06:52 UTC
Labels: Area: ProToCol, bug
