### ISSUE TITLE
[Bug] Some commands change default console colors

### ISSUE THREAD

**Issue by skeeler** [Azure/azure-devops-cli-extension#907] opened 2019-11-28 22:04 UTC
**Describe the bug**
Some azure-devops CLI extension commands change the default console colors, specifically those that issue the statement: "This command group is in preview...". The problem is that subsequent console output (i.e. regular informational text, for example produced by Write-Output) is completely unreadable (black on black).

**To Reproduce**
Azure Cli Version: 2.0.76
Use az --version 
Look for something like-
azure-cli (2.0.70)

Azure-Devops extension version: 0.15.0
Use az --version
Look for something like-
Extensions:
azure-devops (0.15.0)

1. Open Visual Code integrated terminal for PowerShell Core 6
1. login using az login or az devops login
2. Run command "az boards iteration project list --depth 10 --org $orgUrl --project $projectName
3. See "This command group is in preview..." message (blue on black text)
4. Try typing another command in the integrated terminal (PowerShell Core) window, nothing is visible as the console colors for regular text are now black on black.

**Expected behavior**
The only way I've found to recover the proper console colors is to invoke the [Console]::ResetColor() method, but this is a hack and devops cli shouldn't be interfering with the Visual Code PS Core console colors in this way. Note that this only happens in the Visual Code (1.40.2) terminal/console window - the behavior is fine in a PowerShell Core 6 console window.

**Screenshots**

**Debug logs**
Add the output of the command running it with debug mode (--debug)

**Additional context**

**Comment by atbagga** [comment] 2019-11-29 04:42
This behavior comes from Knack which is the base framework used by Azure-Cli and hence all the extensions on AzureCLI. 

I will try to repro it on my end and raise a corresponding issue in Knack and work with that team on getting it fixed.

**Comment by atbagga** [comment] 2019-12-03 06:12
@Skeeler Thank you for reporting the issue. 

The Knack team was able to repro the issue and the fix is in PR.  You can check the above linked issue in Knack repo for the fix. 

Note: Since this is coming from Knack/Azure-CLI, once the issue is fixed you will need to update azure-cli to get the fix (and not azure-devops).

I am closing this issue since it is getting tracked in the knack repo.

**Closed by atbagga** 2019-12-03 06:12 UTC
Labels: Area: ProToCol, bug
