### ISSUE TITLE
Unable to download artifacts from Azure

### ISSUE THREAD

**Issue by javier-intel** [Azure/azure-devops-cli-extension#849] opened 2019-10-24 20:41 UTC
## Describe the bug

**Command Name**
`az artifacts universal download --organization "https://windowspartners.visualstudio.com/" --feed "mcdm_intel_drops" --name "windowsai-discard-prototype" --version "0.0.4" --path .`

Extension Name: azure-devops. Version: 0.8.0.`
[AzureDownloadError.txt](https://github.com/Azure/azure-devops-cli-extension/files/3769390/AzureDownloadError.txt)

**Errors:**
```
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
pip-install-p8t_6awn\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 652, in _run_job
azext_devops\dev\common\exception_handler.py, ln 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-p8t_6awn\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
...
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization "https://windowspartners.visualstudio.com/" --feed "mcdm_intel_drops" --name "windowsai-discard-prototype" --version "0.0.4" --path . --debug`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.75

Extensions:
azure-devops 0.8.0

```

**Comment by shubham90** [comment] 2019-12-13 00:53
This bug occurs when some other process might interfere with the download artifact tool. The process could be an antivirus, some other process which is sharing the same location etc. We are in the process of adding a retry to alleviate this. If the antivirus policy is set to delete the tool, then the path needs to be whitelisted. 

Also, this issue looks like a duplicate of #776 . Closing this one and tracking it there.

**Closed by shubham90** 2019-12-13 00:53 UTC
Labels: Area: Packages, bug
