### ISSUE TITLE
[Feature Request] Allow to set parameters for pipelines runs

### ISSUE THREAD

**Issue by alxy** [Azure/azure-devops-cli-extension#1110] opened 2021-03-07 17:54 UTC
**Is your feature request related to a problem? Please describe.**
It would be nice if I could run pipelines programmatically (from Azure CLI) and set parameteres for the run, as I am also able to when using the ADO pipeline interface. The suggested interface would look like this:
```bash
az pipelines run --id 123 --parameters "{'name': 'value'}"
```
As parameters accept [complex typed values](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#parameter-data-types) I would suggest passing a JSON string.

**Describe the solution you'd like**
The most recent [REST API for pipelines](https://docs.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/run%20pipeline?view=azure-devops-rest-6.0#request-body) runs allows to specify `templateParameters`. Thus, it shoud be possible to implement this feature using this endpoint.

**Additional context**
This feature could come in handy in larger projects to orchestrate automation pipelines, as I am able to queue this pipelines in a particular order with a specific set of parameters and variables.

**Comment by ausfestivus** [comment] 2021-05-10 06:27
This sounds like a dupe of https://github.com/Azure/azure-devops-cli-extension/issues/972

**Comment by gauravsaralMs** [comment] 2021-07-15 11:45
@alxy for our better understanding can you please share if you are able to use `variables` or not in the existing command?
https://docs.microsoft.com/en-us/cli/azure/pipelines?view=azure-cli-latest#az_pipelines_run

or is the ask for something else ?

cc: @roshan-sy

**Comment by alxy** [comment] 2021-07-15 12:32
@gauravsaralMs Azure pipelines support [variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) and [parameters](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script). These are two different concepts (I think parameters are evaluated at queue time, while variables can even be set/changed during runtime of a pipeline), and my request is for the later :)

**Comment by vsuzdaltsev** [comment] 2021-09-03 17:54
up

**Closed** 2021-11-12 10:36 UTC
Labels: Feature, Requires API upgrade
