### ISSUE TITLE
An error occurred while extracting the Universal Packages tooling: [WinError 5] Access is denied: '

### ISSUE THREAD

**Issue by saiprasanthrajavarapu** [Azure/azure-devops-cli-extension#798] opened 2019-09-23 20:12 UTC
## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
pip-install-rg707cll\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 652, in _run_job
azext_devops\dev\common\exception_handler.py, ln 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-rg707cll\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
...
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} --name {} --version {} --description {} --path {} --debug`

## Environment Summary
```
Windows-10-10.0.16299-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.73

Extensions:
azure-devops 0.11.0

```

**Comment by elbatk** [comment] 2019-10-22 15:47
@saiprasanthrajavarapu Do you have any more information here? It looks like there may be an error in either auth or the file path you used. The title says auth but the logs don't contain that error.

**Comment by shubham90** [comment] 2019-12-13 01:05
This bug occurs when some other process might interfere with the download artifact tool. The process could be an antivirus, some other process which is sharing the same location etc. We are in the process of adding a retry to alleviate this. If the antivirus policy is set to delete the tool, then the path needs to be whitelisted. 

Also, this issue looks like a duplicate of #776 . Closing this one and tracking it there.

**Closed by shubham90** 2019-12-13 01:05 UTC
Labels: Area: Packages, bug, question
