### ISSUE TITLE
[Feature Request] Support all merge types when completing a PR

### ISSUE THREAD

**Issue by thorhj** [Azure/azure-devops-cli-extension#786] opened 2019-09-11 04:56 UTC
### Description
Today when I complete a pull request through the Azure DevOps web interface, I get the option to use semi-linear merge (i.e. rebase then no-ff merge onto the trunk) as well as rebase and fast-forward.

![image](https://user-images.githubusercontent.com/4330107/64668800-48362380-d45f-11e9-99da-aaa135311ee8.png)

These two options do not appear to be available through the CLI when using `az repos pr update --status completed` to complete the PR. Only merge (default) and squash (using the `--squash` flag) seems to be available.

### Solution
Add a flags to the `az repos pr update` command for the merge strategies available through the web interface but not currently through the CLI:

```
az repos pr update --status completed --semi-linear-merge
az repos pr update --status completed --rebase
```

Another solution is to create a generel option for merge strategy with the supported merge types as input (this approach makes the command less bloated, but is not in line with the existing options):

```
az repos pr update --status completed --merge-strategy <merge|squash|rebase|semi-linear-merge>
```

**Comment by atbagga** [comment] 2019-09-11 04:59
Duplicate of open issue https://github.com/Azure/azure-devops-cli-extension/issues/546.

**Closed by atbagga** 2019-09-11 04:59 UTC
Labels: Feature
