### ISSUE TITLE
artifact download failed

### ISSUE THREAD

**Issue by ishitam8** [Azure/azure-devops-cli-extension#871] opened 2019-11-05 10:02 UTC
Issue reference from Azure CLI Extension repo
Azure/azure-cli-extensions#1015

**Comment by hakonrossebo** [comment] 2019-11-18 13:33
I'm experiencing the same issue. Is there any workarounds for this until the bug is fixed?

**Comment by hakonrossebo** [comment] 2019-11-20 08:21
As discussed in #776 , this could be related to McAfee as I also have this installed without the possibility to turn this off or change settings.

**Comment by shubham90** [comment] 2019-12-13 00:52
This bug occurs when some other process might interfere with the download artifact tool. The process could be an antivirus, some other process which is sharing the same location etc. We are in the process of adding a retry to alleviate this. If the antivirus policy is set to delete the tool, then the path needs to be whitelisted. 

Also, this issue looks like a duplicate of #776 . Closing this one and tracking it there.

**Closed by shubham90** 2019-12-13 00:52 UTC
Labels: Area: Packages, bug
