### ISSUE TITLE
az pipelines build queue kicks off 3 build requests in azure devops instead of just 1 

### ISSUE THREAD

**Issue by dwhanger** [Azure/azure-devops-cli-extension#628] opened 2019-05-24 18:25 UTC
**Describe the bug**
The command line "az pipelines build queue <org> <project>" kicks off 3 build requests in azure devops instead of just 1 "

**To Reproduce**
login via az login, create an azure devops build, execute the above command line

azure-cli (2.0.65)

Azure-Devops extension version: 
azure-devops (0.8.0)

see above...

**Expected behavior**
only 1 build should be kicked off; also, shouldn't the build, test, and deploy be blocking, as in return when finished?  It would help with the last step I have which is to execute 'az eventgrid event-subscription create' commands to setup event grid subscriptions after a successful build and deploy of functions...

**Comment by atbagga** [comment] 2019-05-28 10:30
This is definitely not an expected behavior. Can you run your command in debug mode and share the logs. 
```
az pipelines build queue --definition-name myproject-ci --debug
```

This should only queue the definition myproject-ci once. 

Regarding the build, test, deploy should be blocking - No, multiple builds can be running in parallel so they are not blocking. 
For your particular use case you will need to build a polling logic in the script to wait for successful completion of the build and then proceed.

**Comment by atbagga** [comment] 2019-05-29 07:47
@dwhanger Can you share the debug logs for this?

**Comment by atbagga** [comment] 2019-06-07 10:45
Closing this due to lack of logs.

**Closed by atbagga** 2019-06-07 10:45 UTC
Labels: Area: ProToCol, bug
