### ISSUE TITLE
az artifacts universal download fails

### ISSUE THREAD

**Issue by praveen-pk** [Azure/azure-devops-cli-extension#847] opened 2019-10-24 00:01 UTC
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.13.0.`

**Errors:**
```
## Following lines are manually added to provide better context.
An error occurred while extracting the Universal Packages tooling: [WinError 5] Access is denied: '~$HOME\\azure\\azuredevops\\cli\\tools\\artifacttool\\xxxxxxx-x-xxxx' -> '~$HOME\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.128'

[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
pip-install-p8t_6awn\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 652, in _run_job
azext_devops\dev\common\exception_handler.py, ln 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-p8t_6awn\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
...
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Freshly install 'azure-devops' extension
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Windows-10-10.0.19002-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.75

Extensions:
azure-devops 0.13.0

```

**Comment by chicoboymax** [comment] 2019-11-07 19:24
I have the same problem, in my case I want to publish an artifact. Did you find a way around this issue ?

**Comment by shubham90** [comment] 2019-12-13 00:46
This bug occurs when some other process might interfere with the download artifact tool. The process could be an antivirus, some other process which is sharing the same location. We are in the process of adding a retry to escape this. 

Also, this issue looks like a duplicate of #798 . Closing this one and tracking it there.

**Closed by shubham90** 2019-12-13 00:46 UTC
Labels: Area: Packages, bug
